version: '3'
services:
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: always

  php:
    image: php:8.0-cli
    restart: always
    volumes:
      - .:/app
    working_dir: /app